### ISSUE TITLE
There should be a custom skirmish option

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#115]
Quicklaunch is fine, but for local singleplayer it's also great to provide custom skirmish option. Where did it go?

**Comment by GoogleFrog** [comment]
You get to the end of the quicklaunch configuration and click "Advanced" in the bottom right instead of the large "Start" in the middle. This creates a skirmish game with the options you selected.

You can also go into Settings -> Lobby and disable "Simple skirmish setup" to go straight  to the custom skirmish window whenever you open it.
