### ISSUE TITLE
Rank icons not updated after ranked games

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#135]
After leveling up(elo or level), the player's rank icon should be updated instantly.

A congratulation window after the game might be neat.

**Comment by gajop** [comment]
I'll implement the update if it's sent.
Separate the congratulation / reward / update to a different issue imo. (I've got some ideas on that as well!)

**Comment by Licho1** [comment]
Rank icons are sent.

**Comment by gajop** [comment]
So, are you sure ranks aren't updated? 
I've tested with Chobby and even cleaned up the code a bit (https://github.com/Spring-Chobby/Chobby/commit/b3abbec63fc324039351d96095562a8f194ca3fa).

Testing was done by simulating the server messages so I can confirm that Chobby behaves correctly. There is no special notification (that's #153), but the icons are properly updated. If there are any issues, they don't seem to be due to Chobby (report/fix on infra).

**Comment by DeinFreund** [comment]
This has been fixed from what I've seen
