### ISSUE TITLE
Display congratulation screen when reaching new level or skill rank

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#153]
Split from #135

**Comment by gajop** [comment]
Imo it's not worth to display a popup when a new level is reached (that happens too often), but it's worth having when the rank icon changes (and I implemented that).
I need some sounds for rank gained and rank lost.
Possibly also distinguish between elo rank gain/level gain instead of just the general "rank gain".

**Comment by Licho1** [comment]
There should simply be debriefing popup that shows progress bar animation, awards, progress to achievements etc..

**Comment by gajop** [comment]
Yes. that too, but it should be a separate issue. This is just for the rank upgrade (and other very significant events)

**Comment by Licho1** [comment]
Its not really different because "important events" happen always after a battle so they can be part of the same 'Debriefing".

**Comment by GoogleFrog** [comment]
Done.
