### ISSUE TITLE
Cannot leave custom room, cannot change spec status

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#207]
1) go to any custom room which is "ingame"
2) try to change to spec
3) try to leave

Debug log shows chobby sending messages but not server responding.
However if i try the same account in ZKL it works fine, so it's not server's fault.

**Comment by GoogleFrog** [comment]
This is incorrect. To reproduce:
1. Join any custom room
2.  Leave
3. Try to change spec (or anything)

The bug is because User is not processed correctly to notice that you left the battle. I suspect something in the server changed because this code has not been changed since I remember it working. Perhaps LeaveBattle was removed recently? However, the server sends enough information currently.

**Comment by Licho1** [comment]
Nothing regarding ordinary battles changed in server recently.
I also noticed that when you hover battles, you see ghost spectators there .. people who joined but are no longer there. Counts are correct but list shows more people than there is. 
Also the fact, that ZKL still works fine despite being untouched for 6 months, suggest it is something in chobby that changed.
