### ISSUE TITLE
Improve lua download queue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#363]
Currently the head of the queue is told to be downloaded regardless of whether there is another download in progress. For VFS downloads this appends the download to the end of the VFS queue. This is problematic in the case where multiple high priority downloads are created, for example in a room with a few rapid map changes.

**Comment by gajop** [comment]
do you need some extra engine API for this?

**Comment by GoogleFrog** [comment]
The ticket is designed to work around the issues with the engine API because I don't expect it to receive updates. A useful thing in the engine would be the ability to cancel the current download.

**Comment by gajop** [comment]
pr-downloader has been getting some updates, although they didn't make it to spring yet due to lack of testing.
So to clarify, a function that allows you to cancel a download based on its ID would be sufficient? That should also cover the special use case when its the current ID.
Are there any other functions you'd like, such as reordering downloads?

**Comment by GoogleFrog** [comment]
I'd like the ability to check whether a download is active or some assurance that the current callins work such that I can reliably determine this with a widget. Other functions would have been nice but I've already reimplemented the download queue in lua.

**Comment by gajop** [comment]
> I'd like the ability to check whether a download is active or some assurance that the current callins work such that I can reliably determine this with a widget.

I'm not sure what such a function would do and what its signature would look like. Something like this?
`VFS.IsDownloadActive(downloadID) -> bool`
`VFS.IsDownloadActive() -> bool`

Determining what active means also needs to be specified. Should it return true when the download was queue but before it started? What should it return in `DownloadFinished`, `DownloadFailed` and `DownloadStarted` callins?

> Other functions would have been nice but I've already reimplemented the download queue in lua.

In case a Lua implementation is relatively easy and provides all functionalities, do you think we should remove the engine queue, to make things simpler?
The reason I wrote it in the engine originally is because we could potentially achieve two things:
- Detect whether downloads are possible before we start them.
- Estimate the size of the items in the queue.

Although I can imagine the above would be doable using Lua, provided there's a more complete API (to search packages and get their sizes). Thoughts?
