### ISSUE TITLE
Matchmaker is putting people into games against CAI

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Chobby#423]
Check this over 1 hour slugfest, this was someones first game and introduction to ZK: http://zero-k.info/Battles/Detail/477106 . New user in question seemed to have a good time and learned stuff, but I think most people wouldn't have had the patience to finish.

CAI dragged out the game by idling entire armies at the back, and showing poor play by building fusions, factories, and other junk on the frontlines.

CircuitAI is much better these days I don't see why it's not used.

**Comment by sprunk** [comment]
Who hosts the Circuit? It cannot be the server (because Circuit requires the simulation to be ran and the server doesn't do that for performance reasons) so it has to be one of the players.

What if said player leaves? What if the assigned player doesn't actually have Circuit installed (eg using some custom lobby which doesnt prevent joining MM without it)?

**Comment by The-Yak** [comment]
I don't understand, circuit comes with ZK these days why would the user not have it installed? Who cares about custom lobby support? Chobby should be the only lobby supported.

CAI creates terrible unfun games.

**Comment by Pestr** [comment]
CAI is very annoying and have not competitive playing style. We played game more one hour and bot don't wanted kill us, but could be do it many times.

**Comment by sprunk** [comment]
>circuit comes with ZK these days why would the user not have it installed?

Corrupt download, for example.

>Player with best system should host Circuit.

How do you weigh CPU vs memory? What if someone is running stuff in the background so has less effective resources? If there are multiple circuits, how do you distribute them among the people based on their system quality?

>If they leave it should be "transferred(?)" to the player with next best system.

Not possible.

**Comment by The-Yak** [comment]
The new download system should help prevent corrupt downloads if I understand it.

> How do you weigh CPU vs memory?

Rank cpu only? It's not perfect but it's typically the bottleneck of spring. Background stuff would be more of an issue if spring was properly multithreaded. Right now with most cpus there is room on the other cores for background stuff.

Unreasonable hard may as well be considered not possible from my perspective, I wouldn't have even brought this up if I knew the amount of work it would take.

**Comment by GoogleFrog** [comment]
There are many problems
1. Who hosts the AI?
2. What is the difficulty level of the AI?
3. A player leaving causes all AIs to leave.
4. What if their circuit is broken or not installed?

(3) is the biggest problem. Matchmaker has to work without players needing to know technical details about AI hosting. How about this solution:
- Everyone hosts one AI.
- If a player leaves all units for that AI are given to an AI that is still present. A gadget should detect that it is a coop MM game and automatically do the transfer.

This solution may be complicated by the merge behaviour of circuit. I don't know what happens if you give units to an AI which previously gave all of its units away for merge. There is an AI option to turn off merge so we could use it as a proof of concept.

Difficulty level is a problem that is hard to solve but we it is not like CAI does better. We could probably put easy circuit in and have a better system than the current one. Broken circuit is highly unlikely and breaks singleplayer as well so it would not be something we could ignore.

**Comment by Licho1** [comment]
Hmm so I am not sure what to do if we really want to change this to circuit ..

**Comment by sprunk** [comment]
Infra task. https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1782
