### ISSUE TITLE
Campaign chobby interface allows illegal commander which does not appear ingame

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Chobby#467]
If Personal Shield is unlocked before level 3 (requires a pretty specific path, but this has been done by at least one user) and then put on a level 2 com, the com does not spawn at the beginning of the mission. Once level 3 is attained the shielded com appears as usual. Of the other modules which appear to be level locked:

- Personal Cloak, Field Radar and Radar Jammer cannot be equipped in anything less than a level 2 slot but cannot be obtained before level 2.
- High Density Plating, Lazarus Device, Flux Amplifier, Disruptor Ammo and Napalm Warhead cannot be equipped in anything less than a Level 3 slot. (Most of them are obtainable before level 2 in theory if you completed no optional objectives. The Plating upgrade in mission 19 might be unlocked by a reasonable player before level 3.)
- Drones do not appear to be equippable at all.

Since unlocking a module but being unable to use it feels bad the best solution may be to disable level restrictions for campaign commanders.

**Comment by GoogleFrog** [comment]
I intended to implement static commander spawning such that it bypasses legality checks.

**Comment by GoogleFrog** [comment]
There were no legality check issues. The issue was specifically with shield because shields are implemented by adding duplicate unitdefs. There was no level 2 shielded commander unitdef generated because usually the shield is not applicable at level 2. This caused an error when the game attempts to spawn a shielded level 2 commander.
