### ISSUE TITLE
IME breaks ingame editboxes

### ISSUE THREAD

**Issue by jiefue** [ZeroK-RTS/Chobby#497]
when skirmish battle , save game can't input file name and description

**Comment by GoogleFrog** [comment]
Are you saying that you cannot type in the boxes?

**Comment by gajop** [comment]
The workaround does more harm than good right now so let's ignore that.
To get editboxes working you need to use the newest version of Chili (Chobby version at https://github.com/ZeroK-RTS/Chobby/commit/dddda034d8306be05470926c2445bae5b0d4e010) both ingame and in lobby. 
Components are now required to send the following commands properly when they want to receive TextInput events:
- Spring.SDLStartTextInput()
- Spring.SDLStopTextInput()

This is done in order to prevent TextInput events when the player is just playing the game and not typing anything. They should not be sending unicode text then.

**Comment by GoogleFrog** [comment]
Stable seems to work for me.
