### ISSUE TITLE
Chobby trying to re-enter MM when it shouldn't.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Chobby#668]
Chobby tries to rejoin MM after loading even if the player just got invited into a MM match, or if he started to play in another match. Chobby should only rejoin MM if the player started spectating a game or playing singleplayer.

This has been going on for longer so the server now prevents users from rejoining MM in these cases, but it's ugly for users to be shown a "You can't rejoin MM" message, when they wouldn't want to anyway.

**Comment by GoogleFrog** [comment]
Are you saying that the server automatically prevents chobby rejoining MM when joining a multiplayer game as a player? That sounds fine, why is any message needed?

> Chobby tries to rejoin MM after loading even if the player just got invited into a MM match

I don't understand this. What do you mean by "just got invited into a MM match"? If you accept a MM match then you leave the matchmaker so won't rejoin.

The simplest solution is probably to disable the rejoin after load. Players can go back and search MM in the lobby if they want to spec and MM at the same time. Otherwise, explain what "when it shouldn't" means.

**Comment by GoogleFrog** [comment]
Still don't know what you mean.

**Comment by DeinFreund** [comment]
See #589

**Comment by GoogleFrog** [comment]
Did you test that?

**Comment by DeinFreund** [comment]
Yes, it is what happens.

**Comment by GoogleFrog** [comment]
This is all too vague. I want an actual point by point list that describes an event that occurred. The ticket you linked is even worse.

**Comment by GoogleFrog** [comment]
I'm just going to close this because I probably fixed whatever it is you're talking about by removing the whole system. You should remove the server-side rejoin block workaround.

**Comment by DeinFreund** [comment]
The server side system still exists as an anti-griefing mechanism. It needs better UI though and can be disabled in the meanwhile by setting the time between matches to zero in dyn config.
