### ISSUE TITLE
After installing, chobby does not try to connect/ask for account details

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#77]
When you first start chobby in a fresh folder, it just starts in offline mode. It makes no attempt to create account or connect to server.

This is fairly important, i dont trhink players can be trusted to locate and click "online" button.

**Comment by GoogleFrog** [comment]
Why does it need to create an account or connect to the server?

**Comment by Licho1** [comment]
How else will it send mission scores and usage stats?

**Comment by GoogleFrog** [comment]
I am not sure. Perhaps the server could support receiving such data without an account. I don't want to hit people with a login screen on launch because MP is scary. Note that I expect the wrapper to tell chobby to auto-register an account with appropriate details if the wrapper is launched with steam. Steam players could be automatically logged in at the start with no need for them to see a login screen.

**Comment by Licho1** [comment]
If wrapper provides a way to login,chobby would still be needed to login to server by itself to establish connection and send stats..  
Are mission run count stats interesting? Are mission scores/offline competition interesting? I would say at least the scores is interesting mechanics that should be kept if possible.

**Comment by GoogleFrog** [comment]
Mission scores are not required. Usage stats are now done online/offline with analytics. If you start chobby through steam it will try to register an account for you and connects automatically to ZKLS.
