### ISSUE TITLE
Check whether the victory condition on planet Tempest works.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#788]

**Comment by HTMLPhoton** [comment]
Can confirm, Does work.

**Comment by GoogleFrog** [comment]
> I've played twice now and I suddenly win around 17:00.
I played it on Easy and Normal.
I've not had the commander leave the base, though the objective is to take him to the artifact.
There is lots of defense surrounding the artifact still, so I don't think the ally had his commander there either.
So I'm not sure what's triggering it, but since it's happened twice I suspect it's a bug.

**Comment by HTMLPhoton** [comment]
Whoops, though you meant if the victory condition actually triggered.

Can reproduce this bug. It happens only when the South AI loses all of their units and when you destroy all of the Starting factories on the Gaia team (Strider hubs and factories gained later by zombie-ressurection does not count). I suspect this causes the South AI to resign (though killing all of their units does not cause them to resign), so prehaps this could be fixed by giving the Artifact to the south AI, preventing them from resigning.

This probably happens on New Falsell, Phisnet and Hastus as well. Will check.
